#!/bin/bash -x

set -o errexit
set -o pipefail
set -o nounset

for unit in /etc/toolbox/systemd-units/common/* ; do
  install -o 0 -g 0 -m 0644 "${unit}" /host-systemd/
done
for unit in /etc/toolbox/systemd-units/basic/* ; do
  install -o 0 -g 0 -m 0644 "${unit}" /host-systemd/
done
